# Generated by Django 3.0.4 on 2020-03-21 18:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompra',
            name='consecutivo',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='total',
        ),
        migrations.AlterField(
            model_name='carrito',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 18, 49, 32, 779929, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 18, 49, 32, 778905, tzinfo=utc)),
        ),
    ]
