# Generated by Django 3.0.4 on 2020-03-21 19:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0003_auto_20200321_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
